name:                harvest-notification
version:             0.1.0.0
github:              "pavelkucera/harvest-notification"
license:             MIT
author:              "Pavel Kucera"
copyright:           "2020 Pavel Kucera"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pavelkucera/harvest-notification#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- process
- req
- text
- time

library:
  source-dirs: src

executables:
  harvest-notification:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - harvest-notification
